---
roles:
  - name: juniper.junos
collections:
  - name: ansible.controller
    version: 4.3.12
  - name: ansible.netcommon
    version: 4.1.0
  - name: ansible.network
    version: 1.2.0
  - name: ansible.posix
    version: 1.3.0
  - name: ansible.security
    version: 1.0.0
  - name: ansible.snmp
    version: 1.0.1
  - name: ansible.utils
    version: 2.7.0
  - name: ansible.yang
    version: 1.0.0
  - name: arista.eos
    version: 6.0.0
  - name: cisco.asa
    version: 4.0.0
  - name: cisco.ios
    version: 4.4.0
  - name: cisco.iosxr
    version: 5.0.0
  - name: cisco.nxos
    version: 4.1.0
  - name: community.general
    version: 4.5.0
  - name: frr.frr
    version: 2.0.0 
  - name: juniper.device
    version: 1.0.2
  - name: junipernetworks.junos
    version: 4.0.0
  - name: openvswitch.openvswitch
    version: 2.1.0
  - name: servicenow.itsm
    version: 1.3.3
  - name: splunk.es
    version: 2.1.0
  - name: vyos.vyos
    version: 4.0.0
