---
## This playbook setup the loopback device for simulating a block device

# Apply common configuration to all hosts
- hosts: all 
  tasks:

  - name: Create a file of 180MB on /mnt/demo to fill up to 90% the disk
    command: dd if=/dev/zero of=/mnt/demo/largefile bs=1M count=180
  
