---
## This playbook show the mounted fs on the system

# Apply common configuration to all hosts
- hosts: all 
  tasks:
     - name: Collect only facts about hardware
       setup:
         gather_subset:
           - 'hardware'

     - name: Test for available disk space
       setup: filter=ansible_mounts
       
     - name: Ensure that free space on the tested volume is greater than 15% of total space
       assert:
         that:
           - mount.size_available > mount.size_total|float * 0.15
         success_msg: Disk space has NOT reached 95% threshold
         fail_msg: Disk space has reached 95% threshold!!!
         quiet: true
       vars:
         mount: "{{ ansible_mounts | selectattr('mount','equalto',item.mount) | list | first }}"
       with_items:
         - "{{ ansible_mounts }}" 

