---
## This playbook show the mounted fs on the system

# Apply common configuration to all hosts
- hosts: all 
  tasks:
 
  - anible.builtin.set_fact: disk_limit=0.8

  - anible.builtin.set_fact:
      mount: "{{ ansible_mounts | first }}"
                                                                                                                        
  - anible.builtin.set_fact: disk_usage="{{ mount.size_total - mount.size_available }}"
  - anible.builtin.set_fact: disk_usage_ratio="{{ disk_usage|float / mount.size_total }}"
  - anible.builtin.set_fact: disk_usage_s="{{ (disk_usage|float / 1000000000) | round(1, 'common') }}GB"
  - anible.builtin.set_fact: disk_total_s="{{ (mount.size_total / 1000000000) | round(1, 'common') }}GB"
  - anible.builtin.set_fact: disk_usage_ratio_s="{{ 100 * (disk_usage_ratio|float) | round(1, 'common') }}%"
  - anible.builtin.set_fact: disk_limit_ratio_s="{{ (100 * disk_limit|float) |round }}%"
                                                                                                                        
  - anible.builtin.debug:
      msg: "disk usage {{ disk_usage_s }} of total {{ disk_total_s }} ({{ disk_usage_ratio_s }}) (should be within limit {{ disk_limit_ratio_s }})"

  - name:                                                                                                                 
    anible.builtin.assert:
      that: ( (disk_usage|float)/mount.size_total ) < disk_limit|float
      msg: "Disk usage {{ disk_usage_ratio_s }} exceeds {{ disk_limit_ratio_s }}"
    tags: disk
    any_errors_fatal: true