---
## This playbook show the mounted fs on the system

# Apply common configuration to all hosts
- name: Filesystem check
  hosts: all
  tasks:
     - name: Collect only facts about hardware
       anible.builtin.setup:
         gather_subset:
           - 'hardware'

     - name: Test for available disk space
       anible.builtin.setup: filter=ansible_mounts
       
     - name: Ensure that free space on the tested volume is greater than 10% of total space
       anible.builtin.assert:
         that:
           - mount.size_available > mount.size_total|float * 0.1
         success_msg: Disk space has NOT reached 90% threshold
         fail_msg: Disk space has reached 90% threshold!!!
         quiet: true
       vars:
         mount: "{{ ansible_mounts | selectattr('mount','equalto',item.mount) | list | first }}"
       with_items:
         - "{{ ansible_mounts }}" 

