---
- name: network stats command playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:
    - name: show interface stats command
      cli_command:
        command: "show interface GigabitEthernet1"
      when: ansible_network_os is defined
      register: output

    - debug:
        msg: "{{ output.stdout_lines }}"
