---
- name: reload cli command playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:
    - name: reload command
      cli_command:
        command: "reload\ny"
      when: ansible_network_os is defined

    - name: Wait for the reboot to complete if there was a change.
      wait_for_connection:
        connect_timeout: 10
        sleep: 5
        delay: 5
        timeout: 400


