---
- name: reload cli command playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:
    - name: reload command
      cli_command:
        command: "reload"
      when: ansible_network_os is defined
      register: output

    - debug:
        msg: "{{ output.stdout_lines }}"
