---
- name: show version cli command playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:
    - name: show version command
      cli_command:
        command: "show version"
      when: ansible_network_os is defined
      register: output

    - name: Update incident
      servicenow.itsm.incident:
        number: "{{ SNOW_INC_NUMBER }}"
        instance:
          host: "{{ SNOW_HOST }}"
          username: "{{ SNOW_USER }}"
          password: "{{ SNOW_PASS }}"
          timeout: "{{ SNOW_TIMEOUT }}"
        state: in_progress
        other: 
          comments: "Ansible Automation Platform output of "show version" command:\n{{ output.stdout_lines }}"

#    - debug:
#        msg: "{{ output.stdout_lines }}"
