---
- name: show version cli command playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli

  tasks:
    - name: show version command
      cli_command:
        command: "show version"
      when: ansible_network_os is defined
      register: output

    - debug:
        msg: "{{ output.stdout_lines }}"
