---
- name: Automate SNOW 
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm

  tasks:

    # Always give your tasks a useful name
    - name: List all incidents

      servicenow.itsm.incident_info:
        instance:
          host: "{{ SNOW_HOST }}"
          username: "{{ SNOW_USER }}"
          password: "{{ SNOW_PASS }}"
      register: result

    - debug:
        var: result
        verbosity: 2
